CREATE TABLE ST_02_AUTHENTIFIER_TUSER
(
  ID VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(20)
, CONSTRAINT ST_02_AUTHENTIFIER_TUSER_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
;


INSERT INTO "BUEHLS"."ST_02_AUTHENTIFIER_TUSER" (ID, PASSWORD) VALUES ('sb', 'blah')